import { EngineeringStore, makeDemo, TYPES, Camera, clone, uid, snap, clamp, nodeBounds, transform, portPosition, routeEdge, validateEngineering, validateProject, distance, csv } from './core.js';
import { EngineeringScene, symbolGeometry, geometryToSVG, geometryToDXF, PALETTE } from './geometry.js';
import { DiagramRenderer } from './renderer.js';
import { ProjectStorage } from './storage.js';
import { icon, hydrateIcons, symbolIcon, el, esc, typeIcon, toast, downloadFile } from './ui.js';

const storage=new ProjectStorage();
let initial;
try{const saved=await storage.load();initial=saved?validateProject(saved):makeDemo();}catch(error){console.warn('Saved project was not loaded:',error);initial=makeDemo();toast('Saved project could not be loaded. The sample project is open.',true);}
const store=new EngineeringStore(initial),scene=new EngineeringScene(),camera=new Camera();
const state={docId:store.documents[0].id,view:'diagram',selected:new Set(store.nodes.has('p101a')?['p101a']:[]),tool:'select',insertType:null,nav:'units',library:'Equipment',inspector:'attributes',table:'equipment',ribbon:'engineering',grid:true,snap:true,ortho:true,labels:true,minimap:true,layers:{equipment:true,piping:true,instruments:true,annotations:true},collapsed:new Set(),pointer:null,hover:null,port:null,drag:null,connection:null,marquee:null,space:false,clipboard:null,sort:{key:'tag',direction:1},sceneDirty:true,uiDirty:true,raf:0,savedVersion:store.version,saveTimer:0,frameCount:0,tableSearch:'',treeSearch:'',paletteIndex:0,paletteResults:[],activeRegister:'equipment',openDocs:store.documents.map(d=>d.id),visibleKey:'',visibleData:null};
const editor=el('editor-area'),overlay=el('overlay'),background=el('background');
let renderer;
renderer=new DiagramRenderer(el('gpu'),el('fallback'),(name,reason)=>{el('renderer-status').innerHTML=`<i></i><span>${name==='WebGPU'?'WebGPU accelerated':'Canvas 2D fallback'}</span>`;el('renderer-status').title=reason;invalidate();});
const doc=()=>store.documents.find(d=>d.id===state.docId)||store.documents[0];
const selectedObject=()=>{const id=[...state.selected][0];return store.nodes.get(id)||store.edges.get(id);};
const selectionNodes=()=>[...state.selected].map(id=>store.nodes.get(id)).filter(Boolean);
const allObjects=()=>[...store.nodes.values(),...store.edges.values()];
const objectFor=id=>store.nodes.get(id)||store.edges.get(id);
const wrapError=fn=>{try{return fn();}catch(error){console.error(error);toast(error.message||String(error),true);}};

function invalidate({scene:dirty=false,ui=false}={}){state.sceneDirty||=dirty;state.uiDirty||=ui;if(!state.raf)state.raf=requestAnimationFrame(render);}
function rebuild(){scene.update(store,state.docId,state.layers);state.sceneDirty=false;state.visibleKey='';}
function resize(){const r=editor.getBoundingClientRect();if(r.width<1||r.height<1)return;const dpr=Math.min(window.devicePixelRatio||1,2.5);camera.width=r.width;camera.height=r.height;for(const c of [overlay,background]){const w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(c.width!==w||c.height!==h){c.width=w;c.height=h;}}renderer.resize(r.width,r.height,dpr);invalidate();}
new ResizeObserver(resize).observe(editor);
window.addEventListener('resize',resize);
function fit(){if(state.view!=='diagram')setView('diagram',state.docId);resize();const d=doc();camera.fit({x:0,y:0,maxX:d.width,maxY:d.height},36);invalidate();}
function frameObject(id){const o=objectFor(id);if(!o)return;if(o.docId!==state.docId||state.view!=='diagram')setView('diagram',o.docId,false);select([id]);if(o.kind==='node'){camera.x=o.x;camera.y=o.y;camera.zoom=clamp(Math.max(camera.zoom,1.1),.4,2.5);}else{const pts=routeEdge(o,store.nodes);camera.fit({x:Math.min(...pts.map(p=>p.x))-100,y:Math.min(...pts.map(p=>p.y))-100,maxX:Math.max(...pts.map(p=>p.x))+100,maxY:Math.max(...pts.map(p=>p.y))+100},70);}invalidate();}
function renderSelectionUI(){
  el('selection-count').textContent=state.selected.size?`${state.selected.size} object${state.selected.size>1?'s':''} selected`:'No selection';
  document.querySelectorAll('[data-object]').forEach(row=>{row.classList.toggle('selected',state.selected.has(row.dataset.object));row.setAttribute('aria-selected',String(state.selected.has(row.dataset.object)));});
  document.querySelectorAll('[data-row]').forEach(row=>row.classList.toggle('selected',state.selected.has(row.dataset.row)));
  renderInspector();
}
function select(ids,{add=false}={}){if(!add)state.selected.clear();for(const id of ids)if(objectFor(id))state.selected.add(id);renderSelectionUI();invalidate();}
function setView(view,id=state.docId,fitPage=true){cancelInteraction();state.view=view;state.docId=id;if(!state.openDocs.includes(id)&&store.documents.some(d=>d.id===id))state.openDocs.push(id);state.selected=new Set([...state.selected].filter(id=>objectFor(id)?.docId===state.docId));editor.classList.toggle('hidden',view!=='diagram');el('register-view').classList.toggle('hidden',view==='diagram');el('data-panel').classList.toggle('hidden',view!=='diagram');document.querySelector('.bottom-resize').classList.toggle('hidden',view!=='diagram');invalidate({scene:true,ui:true});if(view==='diagram')requestAnimationFrame(()=>{resize();if(fitPage)fit();});}
function setTool(tool,type=null){cancelInteraction();state.tool=tool;state.insertType=type;state.port=null;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));document.querySelectorAll('.symbol-card').forEach(b=>b.classList.toggle('active',b.dataset.symbol===type));overlay.style.cursor=tool==='pan'?'grab':tool==='select'?'default':'crosshair';el('tool-hint').textContent=tool==='insert'?`Place ${TYPES[type].label} · Click to insert · Esc to cancel`:tool==='pipe'||tool==='signal'||tool==='cable'?'Click a port to start · Click bends · Click a port to finish · Enter for a free endpoint':tool==='text'?'Click the drawing to place a text annotation':tool==='pan'?'Drag to pan · Scroll to zoom · V to select':'Select an object to inspect · Scroll to zoom · Space to pan';el('status-message').textContent=tool==='insert'?TYPES[type].label:tool[0].toUpperCase()+tool.slice(1);invalidate();}
function cancelInteraction(){if(state.drag&&store.pending)store.cancel();state.drag=null;state.connection=null;state.marquee=null;invalidate({scene:true});}
function localPoint(event){const r=overlay.getBoundingClientRect();return{x:event.clientX-r.left,y:event.clientY-r.top};}
function snapped(p){return state.snap?{x:snap(p.x),y:snap(p.y)}:p;}
function findPort(p,exclude=new Set()){
  let result=null,best=13/camera.zoom;const ids=scene.index.query({x:p.x-best-10,y:p.y-best-10,maxX:p.x+best+10,maxY:p.y+best+10});
  for(const id of ids){const n=store.nodes.get(id);if(!n||exclude.has(id))continue;for(const name of TYPES[n.type].ports){const q=portPosition(n,name),d=distance(p,q);if(d<best){best=d;result=q;}}}return result;
}
function endpointAt(p){const port=findPort(p);return port?{node:port.node,port:port.port}:snapped(p);}
function endpointWorld(p){return p.node?portPosition(store.nodes.get(p.node),p.port):p;}
function handleHit(p){
  if(state.selected.size!==1)return null;const o=selectedObject();if(!o)return null;const tolerance=9/camera.zoom;
  if(o.kind==='node'){
    const rp=transform(o,0,-o.h/2-27/camera.zoom);if(distance(p,rp)<tolerance)return{type:'rotate',id:o.id};
    for(const [sx,sy]of[[-1,-1],[1,-1],[1,1],[-1,1]])if(distance(p,transform(o,sx*o.w/2,sy*o.h/2))<tolerance)return{type:'resize',id:o.id,sx,sy};
  }else{const pts=routeEdge(o,store.nodes);for(let i=0;i<pts.length;i++)if(distance(p,pts[i])<tolerance)return{type:i===0||i===pts.length-1?'endpoint':'waypoint',id:o.id,index:i,end:i===0?'from':'to',points:pts};}
  return null;
}
function render(){
  state.raf=0;if(state.uiDirty){renderUI();state.uiDirty=false;}if(state.view!=='diagram')return;const start=performance.now();
  if(state.sceneDirty)rebuild();
  const b=camera.bounds,pad=55/camera.zoom,bounds={x:b.x-pad,y:b.y-pad,maxX:b.maxX+pad,maxY:b.maxY+pad};
  const visibleIds=[...scene.index.query(bounds)].sort();const key=scene.revision+'|'+visibleIds.join(',');if(state.visibleKey!==key){state.visibleKey=key;state.visibleData=scene.visible(bounds);}
  const data=state.visibleData||{lines:[],fills:[],texts:[],count:0};
  drawBackground();renderer.render(data,camera,key);drawOverlay(data);drawMinimap();
  el('zoom-label').textContent=Math.round(camera.zoom*100)+'%';state.frameCount++;
  el('render-stats').textContent=`${data.count} visible · ${renderer.drawCalls} draws · ${(performance.now()-start).toFixed(1)} ms CPU`;
}
function worldContext(canvas){const c=canvas.getContext('2d'),dpr=canvas.width/camera.width;c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,camera.width,camera.height);c.translate(camera.width/2,camera.height/2);c.scale(camera.zoom,camera.zoom);c.translate(-camera.x,-camera.y);return c;}
function drawBackground(){
  const c=worldContext(background),d=doc(),z=camera.zoom,b=camera.bounds;c.fillStyle='#e9eef0';c.fillRect(b.x,b.y,b.maxX-b.x,b.maxY-b.y);
  c.shadowColor='#244b5a14';c.shadowBlur=12/z;c.shadowOffsetY=3/z;c.fillStyle='#fff';c.fillRect(0,0,d.width,d.height);c.shadowColor='transparent';c.shadowBlur=0;c.shadowOffsetY=0;
  c.save();c.beginPath();c.rect(30,30,d.width-60,d.height-60);c.clip();
  if(state.grid){let step=20;while(step*z<9)step*=2;const startX=Math.max(40,Math.floor(b.x/step)*step),startY=Math.max(40,Math.floor(b.y/step)*step),endX=Math.min(d.width-30,b.maxX),endY=Math.min(d.height-30,b.maxY);c.fillStyle='#e3ebeb';c.beginPath();for(let x=startX;x<endX;x+=step)for(let y=startY;y<endY;y+=step)c.rect(x,y,.8/z,.8/z);c.fill();}c.restore();
  c.strokeStyle='#cedade';c.lineWidth=1/z;c.strokeRect(30,30,d.width-60,d.height-60);
  c.fillStyle='#40616b';c.font='600 14px Inter, Segoe UI, Arial';c.fillText(store.meta.name.toUpperCase().slice(0,60)+'  /  ENGINEERING',62,73);c.font='500 25px Inter, Segoe UI, Arial';c.fillStyle='#355561';c.fillText(d.name.toUpperCase(),62,111);c.font='11px Inter, Segoe UI, Arial';c.fillStyle='#93a5ab';c.fillText(`${d.type==='electrical'?'ELECTRICAL SINGLE-LINE DIAGRAM':'PIPING & INSTRUMENTATION DIAGRAM'}     /     ${store.meta.number}     /     ${d.code}`,63,136);
  c.beginPath();c.moveTo(61,158);c.lineTo(d.width-61,158);c.strokeStyle='#e2e9eb';c.lineWidth=1;c.stroke();
  let lx=d.width-265,ly=81;for(const [text,color,dash]of[['Process line',PALETTE.pipe,false],['Instrument signal',PALETTE.signal,true],['Equipment boundary','#b8c9cb',true]]){c.beginPath();c.moveTo(lx,ly);c.lineTo(lx+37,ly);c.strokeStyle=color;c.setLineDash(dash?[5,4]:[]);c.lineWidth=1.7;c.stroke();c.setLineDash([]);c.font='10px Inter, Segoe UI, Arial';c.fillStyle='#8c9fa8';c.fillText(text,lx+48,ly+3);ly+=21;}
  const y=d.height-95;c.strokeStyle='#c9d7db';c.lineWidth=1;c.beginPath();c.moveTo(30,y);c.lineTo(d.width-30,y);c.moveTo(d.width-500,y);c.lineTo(d.width-500,d.height-30);c.moveTo(d.width-235,y);c.lineTo(d.width-235,d.height-30);c.stroke();
  c.fillStyle='#47716e';c.font='600 20px Inter, Segoe UI, Arial';c.fillText('NEXORA',53,y+30);c.font='9px Inter, Segoe UI, Arial';c.fillStyle='#92a3ab';c.fillText('CONNECTED PLANT ENGINEERING',54,y+48);c.font='13px Inter, Segoe UI, Arial';c.fillStyle='#607d87';c.fillText(d.name,235,y+29);c.font='10px Inter, Segoe UI, Arial';c.fillStyle='#9aaaae';c.fillText(store.meta.name.slice(0,55)+' · Not for construction',235,y+47);
  c.font='9px Inter, Segoe UI, Arial';c.fillText('DRAWING NUMBER',d.width-483,y+18);c.fillText('REVISION',d.width-219,y+18);c.fillStyle='#587381';c.font='600 15px Inter, Segoe UI, Arial';c.fillText(`${store.meta.number}-${d.code}`,d.width-483,y+42);c.fillText(d.revision,d.width-219,y+42);c.font='9px Inter, Segoe UI, Arial';c.fillStyle='#9caaaf';c.fillText('SHEET 1 OF 1',d.width-128,y+43);
  for(let i=1;i<=7;i++){const x=30+i*(d.width-60)/8;c.font='9px Arial';c.fillStyle='#9dabb2';c.fillText(String(i),x,22);c.fillText(String(i),x,d.height-15);}
}
function drawOverlay(data){
  const c=worldContext(overlay),z=camera.zoom;c.textBaseline='middle';
  if(state.labels)for(const t of data.texts){if(t.size*z<4)continue;c.font=`${t.weight} ${t.size}px Inter, Segoe UI, Arial`;c.textAlign=t.align==='left'?'left':'center';if(t.background){const w=c.measureText(t.text).width;c.fillStyle='#ffffffed';c.fillRect(t.x-w/2-3,t.y-t.size/2-2,w+6,t.size+4);}c.fillStyle=t.color;c.fillText(t.text,t.x,t.y);}
  c.textAlign='center';
  for(const id of state.selected){const o=objectFor(id);if(!o||o.docId!==state.docId||state.layers[o.layer]===false)continue;c.strokeStyle='#008d83';c.fillStyle='#0896890b';c.lineWidth=1.1/z;
    if(o.kind==='node'){const b=nodeBounds(o);c.save();c.translate(o.x,o.y);c.rotate((o.rotation||0)*Math.PI/180);c.setLineDash([4/z,3/z]);c.fillRect(-o.w/2-5/z,-o.h/2-5/z,o.w+10/z,o.h+10/z);c.strokeRect(-o.w/2-5/z,-o.h/2-5/z,o.w+10/z,o.h+10/z);c.setLineDash([]);if(state.selected.size===1){for(const [x,y]of[[-o.w/2,-o.h/2],[o.w/2,-o.h/2],[o.w/2,o.h/2],[-o.w/2,o.h/2]]){c.fillStyle='white';c.fillRect(x-3/z,y-3/z,6/z,6/z);c.strokeRect(x-3/z,y-3/z,6/z,6/z);}c.beginPath();c.moveTo(0,-o.h/2-6/z);c.lineTo(0,-o.h/2-23/z);c.stroke();c.beginPath();c.arc(0,-o.h/2-27/z,3.5/z,0,Math.PI*2);c.fillStyle='white';c.fill();c.stroke();}c.restore();}
    else {const points=routeEdge(o,store.nodes);c.beginPath();points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.lineWidth=4/z;c.strokeStyle='#008d8344';c.stroke();c.lineWidth=1/z;c.strokeStyle='#008d83';for(const p of points){c.fillStyle='white';c.fillRect(p.x-3/z,p.y-3/z,6/z,6/z);c.strokeRect(p.x-3/z,p.y-3/z,6/z,6/z);}}
  }
  const portNodes=new Set([...state.selected]);if(state.hover)portNodes.add(state.hover);if(state.port)portNodes.add(state.port.node);
  for(const id of portNodes){const n=store.nodes.get(id);if(!n||n.docId!==state.docId||state.layers[n.layer]===false)continue;for(const name of TYPES[n.type].ports){const p=portPosition(n,name);c.beginPath();c.arc(p.x,p.y,2.7/z,0,Math.PI*2);c.fillStyle='#fff';c.strokeStyle='#499f97';c.lineWidth=1/z;c.fill();c.stroke();}}
  if(state.port){c.beginPath();c.arc(state.port.x,state.port.y,7/z,0,Math.PI*2);c.fillStyle='#00a08c22';c.strokeStyle='#00a08c';c.lineWidth=1.4/z;c.fill();c.stroke();}
  if(state.marquee){const a=state.marquee.start,b=state.marquee.end;c.fillStyle='#0e99850d';c.strokeStyle='#008e85';c.lineWidth=1/z;c.setLineDash([4/z,3/z]);c.fillRect(a.x,a.y,b.x-a.x,b.y-a.y);c.strokeRect(a.x,a.y,b.x-a.x,b.y-a.y);c.setLineDash([]);}
  if(state.connection&&state.pointer){const conn=state.connection,to=state.port?{node:state.port.node,port:state.port.port}:snapped(state.pointer);const edge={from:conn.from,to,waypoints:conn.waypoints,orthogonal:state.ortho};const points=routeEdge(edge,store.nodes);c.beginPath();points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.strokeStyle=conn.type==='signal'?PALETTE.signal:PALETTE.pipe;c.lineWidth=2/z;c.setLineDash([6/z,4/z]);c.stroke();c.setLineDash([]);for(const p of points){c.fillStyle='#fff';c.strokeStyle='#299d8c';c.beginPath();c.arc(p.x,p.y,3/z,0,Math.PI*2);c.fill();c.stroke();}}
  if(state.tool==='insert'&&state.insertType&&state.pointer){const p=snapped(state.pointer),def=TYPES[state.insertType],g=symbolGeometry({x:p.x,y:p.y,w:def.w,h:def.h,type:state.insertType,tag:'',description:'',rotation:0});c.globalAlpha=.55;c.strokeStyle=PALETTE.accent;c.lineWidth=1.5/z;for(const l of g.lines){c.beginPath();c.moveTo(l.a.x,l.a.y);c.lineTo(l.b.x,l.b.y);c.stroke();}c.globalAlpha=1;}
}
const minimapCache={canvas:document.createElement('canvas'),key:''};
function drawMinimap(){
  const canvas=el('minimap'),c=canvas.getContext('2d'),d=doc();c.clearRect(0,0,canvas.width,canvas.height);if(!state.minimap)return;
  const scale=Math.min((canvas.width-14)/d.width,(canvas.height-12)/d.height),ox=(canvas.width-d.width*scale)/2,oy=(canvas.height-d.height*scale)/2,key=state.docId+'|'+scene.revision;
  if(minimapCache.key!==key){minimapCache.key=key;minimapCache.canvas.width=canvas.width;minimapCache.canvas.height=canvas.height;const b=minimapCache.canvas.getContext('2d');b.translate(ox,oy);b.scale(scale,scale);b.fillStyle='white';b.fillRect(0,0,d.width,d.height);
    for(const entry of scene.entries.values()){if(entry.object.type==='zone'||entry.object.type==='text')continue;b.strokeStyle=entry.object.kind==='edge'?(entry.object.type==='signal'?'#aa98c0':'#88aca5'):'#91a7ab';b.lineWidth=1/scale;b.beginPath();for(const line of entry.lines){b.moveTo(line.a.x,line.a.y);b.lineTo(line.b.x,line.b.y);}b.stroke();}}
  c.drawImage(minimapCache.canvas,0,0);c.save();c.translate(ox,oy);c.scale(scale,scale);const bounds=camera.bounds;c.fillStyle='#00867e0e';c.fillRect(bounds.x,bounds.y,bounds.maxX-bounds.x,bounds.maxY-bounds.y);c.strokeStyle='#00867e';c.lineWidth=1/scale;c.strokeRect(bounds.x,bounds.y,bounds.maxX-bounds.x,bounds.maxY-bounds.y);c.restore();
}

async function saveLocal(manual=false){clearTimeout(state.saveTimer);const version=store.version;el('save-state').textContent='Saving…';try{await storage.save(store.serialize());state.savedVersion=version;el('save-state').innerHTML=icon('check',12)+'Saved locally';if(manual)toast('Project saved to this browser. Export JSON for a portable backup.');}catch(error){el('save-state').textContent='Local save failed';toast('Browser storage is unavailable or full. Export a JSON backup.',true);}}
store.subscribe(({label})=>{state.selected=new Set([...state.selected].filter(id=>objectFor(id)));if(!store.documents.some(d=>d.id===state.docId))state.docId=store.documents[0].id;state.openDocs=state.openDocs.filter(id=>store.documents.some(d=>d.id===id));el('save-state').textContent='Unsaved changes';clearTimeout(state.saveTimer);state.saveTimer=setTimeout(()=>saveLocal(),500);invalidate({scene:true,ui:true});});
window.addEventListener('beforeunload',e=>{if(state.savedVersion!==store.version||store.pending){e.preventDefault();e.returnValue='';}});

// ---------- Desktop workbench views ----------
function renderUI(){
  el('project-title').textContent=store.meta.name;el('project-number').textContent=store.meta.number;el('tree-project-name').textContent=store.meta.name;
  el('document-breadcrumb').textContent=state.view==='diagram'?doc().name:state.view==='documents'?'Document management':'Object register';
  el('document-title').textContent=state.view==='diagram'?doc().name:state.view==='documents'?'Project documents':'Engineering object register';
  el('document-revision').textContent='Rev '+doc().revision;document.querySelector('.working-layer .tag').textContent=doc().revision;el('sheet-code').textContent=doc().code;
  el('object-count').textContent=allObjects().length+' objects';el('selection-count').textContent=state.selected.size?`${state.selected.size} object${state.selected.size>1?'s':''} selected`:'No selection';
  document.querySelectorAll('[data-action="undo"]').forEach(b=>b.disabled=!store.undoStack.length);document.querySelectorAll('[data-action="redo"]').forEach(b=>b.disabled=!store.redoStack.length);
  renderDocumentTabs();renderTree();renderInspector();renderTable();if(state.view!=='diagram')renderRegister();
}
function renderDocumentTabs(){el('document-tabs').innerHTML=state.openDocs.map(id=>store.documents.find(d=>d.id===id)).filter(Boolean).map(d=>`<button class="doc-tab ${state.view==='diagram'&&d.id===state.docId?'active':''}" data-doc="${esc(d.id)}">${icon(d.type==='electrical'?'lightning':'diagram')}<span class="doc-code">${esc(d.code)}</span><span>${esc(d.name)}</span><span class="doc-close" data-close-doc="${esc(d.id)}" title="Close tab">×</span></button>`).join('')+`<button class="doc-tab ${state.view==='register'?'active':''}" data-action="register">${icon('table')}Object register</button><button class="doc-add" data-action="new-document" title="Create drawing">${icon('plus',14)}</button>`;}
function renderRibbon(){const button=(a,label,ico,cls='')=>`<button class="ribbon-btn ${cls}" data-action="${a}">${icon(ico,22)}<span>${label}</span></button>`;const small=(a,label,ico)=>`<button class="ribbon-small" data-action="${a}">${icon(ico,14)}${label}</button>`;const group=(label,body)=>`<div class="ribbon-group">${body}<div class="ribbon-group-label">${label}</div></div>`;let html='';
  if(state.ribbon==='engineering')html=group('Objects',button('insert-pump','Equipment','pump','primary')+button('insert-valve','Valve','valve')+button('insert-instrument','Instrument','instrument'))+group('Connections',button('tool-pipe','Process pipe','pipe')+button('tool-signal','Signal line','signal')+button('tool-cable','Cable','cable'))+group('Edit drawing',button('tool-select','Select','pointer')+`<div class="ribbon-small-stack">${small('rotate','Rotate','rotate')}${small('duplicate','Duplicate','copy')}</div>`+`<div class="ribbon-small-stack">${small('align-left','Align left','align')}${small('distribute','Distribute','distribute')}</div>`)+group('Annotations',button('tool-text','Text','text')+button('insert-zone','Area','box'))+group('Engineering data',button('register','Object register','table')+button('datasheet','Datasheet','document'))+group('Consistency',button('validate','Validate','shield','review')+button('revisions','Revisions','history'));
  if(state.ribbon==='home')html=group('Project',button('new-project','New project','project','primary')+button('open','Open','folderopen')+button('save','Save','save'))+group('Documents',button('new-document','New drawing','diagram')+button('documents','Documents','folder')+button('export-json','Export project','export'))+group('History',button('undo','Undo','undo')+button('redo','Redo','redo'))+group('Clipboard',button('copy','Copy','copy')+button('paste','Paste','clipboard')+button('delete','Delete','trash'))+group('Workspace',button('fit','Fit drawing','fit')+button('layers','Layers','layers')+button('search','Find','search'));
  if(state.ribbon==='review')html=group('Quality assurance',button('validate','Consistency','shield','primary')+button('messages','Issues','warning')+button('approve','Approve','check'))+group('Revision management',button('capture-revision','New baseline','history')+button('revisions','Revision history','compare'))+group('Review tools',button('tool-text','Add note','text')+button('focus-selection','Locate object','locate')+button('datasheet','Object data','document'))+group('Deliverables',button('export-svg','Export SVG','export')+button('export-png','Export PNG','download')+button('print','Print drawing','print'));
  if(state.ribbon==='data')html=group('Engineering registers',button('register','Equipment','table','primary')+button('instrument-register','Instruments','instrument')+button('pipeline-register','Pipelines','pipe'))+group('Project documents',button('documents','Documents','folder')+button('datasheet','Datasheet','document')+button('new-document','New drawing','diagram'))+group('Exchange',button('export-json','Project JSON','database')+button('export-csv','Register CSV','table')+button('export-dxf','Drawing DXF','export')+button('open','Import project','folderopen'));
  el('ribbon').innerHTML=html+`<div class="ribbon-caption"><span class="caption-icon">${icon('link',22)}</span><div><strong>Everything, connected.</strong><small>One intelligent plant model.</small></div></div>`;document.querySelectorAll('[data-ribbon]').forEach(b=>b.classList.toggle('active',b.dataset.ribbon===state.ribbon));}
function renderTree(){
  const q=state.treeSearch.toLowerCase(),matches=o=>!q||`${o.tag} ${o.description} ${o.type} ${o.unit}`.toLowerCase().includes(q);
  const row=(o,level=0)=>`<button class="tree-row ${state.selected.has(o.id)?'selected':''} ${o.layer==='instruments'?'instrument':''}" data-object="${esc(o.id)}" role="treeitem" aria-selected="${state.selected.has(o.id)}" style="padding-left:${22+level*12}px">${icon(typeIcon(o.type),13)}<span class="tree-tag">${esc(o.tag)}</span><span class="tree-desc">${esc(o.description)}</span></button>`;
  const group=(id,title,ico,body,count=0)=>`<div class="tree-group"><button class="tree-row folder" data-tree-group="${esc(id)}" aria-expanded="${!state.collapsed.has(id)}"><span class="tree-expand">${state.collapsed.has(id)?'›':'⌄'}</span>${icon(ico,14)}<span class="tree-tag">${esc(title)}</span><span class="tree-count">${count||''}</span></button><div class="tree-children ${state.collapsed.has(id)&&!q?'collapsed':''}">${body}</div></div>`;
  let html='';
  if(state.nav==='units'||state.nav==='locations'){
    const names=state.nav==='locations'?{'U-100':'L-01 · Utility building','U-200':'L-02 · Compressor house','E-100':'L-03 · Electrical room'}:{'U-100':'U-100 · Cooling water','U-200':'U-200 · Instrument air','E-100':'E-100 · Electrical'};
    const units=[...new Set([...store.nodes.values()].map(n=>n.unit))];
    for(const unit of units){const nodes=[...store.nodes.values()].filter(n=>n.unit===unit&&matches(n)&&!['zone','text','junction'].includes(n.type));if(q&&!nodes.length)continue;const docs=[...new Set(nodes.map(n=>n.docId))].map(id=>store.documents.find(d=>d.id===id));let body=docs.map(d=>`<button class="tree-row document" data-doc="${esc(d.id)}" style="padding-left:22px">${icon('diagram')}<span class="tree-tag">${esc(d.code)}</span><span class="tree-desc">${esc(d.name)}</span></button>`).join('');
      const categories=['Equipment','Valves','Instrumentation','Electrical','Connections'];for(const category of categories){const a=nodes.filter(n=>TYPES[n.type].category===category);if(a.length)body+=group(unit+category,category,category==='Instrumentation'?'instrument':category==='Valves'?'valve':'folder',a.map(n=>row(n,1)).join(''),a.length);}
      html+=group(unit,names[unit]||unit,'folder',body,nodes.length);
    }
  }else if(state.nav==='documents'){html=store.documents.map(d=>group(d.id,`${d.code} · ${d.name}`,'diagram',[...store.nodes.values()].filter(n=>n.docId===d.id&&matches(n)).map(n=>row(n)).join(''))).join('');html+=`<button class="tree-row" data-action="new-document" style="padding-left:25px;color:var(--accent)">${icon('plus')}New drawing</button>`;}
  else{for(const category of [...new Set(Object.values(TYPES).map(t=>t.category))])html+=group(category,category,'folder',Object.entries(TYPES).filter(([k,t])=>t.category===category&&(!q||t.label.toLowerCase().includes(q))).map(([k,t])=>`<button class="tree-row" data-symbol="${k}" style="padding-left:24px">${icon(typeIcon(k))}<span class="tree-tag">${t.label}</span></button>`).join(''));}
  el('tree').innerHTML=html||'<div class="empty-state">No matching objects.</div>';document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===state.nav));
}
function renderLibrary(){let types=Object.entries(TYPES).filter(([,d])=>state.library==='Connections'?['Connections','Annotations'].includes(d.category):d.category===state.library);el('symbols').innerHTML=types.map(([type,d])=>`<button class="symbol-card ${type===state.insertType?'active':''}" data-symbol="${type}" draggable="true" title="Place ${d.label}">${symbolIcon(type)}<span>${d.label}</span></button>`).join('');document.querySelectorAll('[data-library]').forEach(b=>b.classList.toggle('active',b.dataset.library===state.library));}
function propertyField(o,key,label,unit='',full=false,options=null){const value=key.startsWith('props.')?o.props[key.slice(6)]??'':o[key]??'';let input=options?`<select data-property="${key}" data-id="${esc(o.id)}">${options.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select>`:key==='description'?`<textarea data-property="${key}" data-id="${esc(o.id)}">${esc(value)}</textarea>`:`<input class="${key==='tag'?'primary':''}" data-property="${key}" data-id="${esc(o.id)}" value="${esc(value)}" ${['x','y','w','h','rotation'].includes(key)?'type="number" step="1"':''} aria-label="${esc(label)}">`;if(unit)input=`<div class="field-unit">${input}<span>${esc(unit)}</span></div>`;return `<label class="property-field ${full?'full':''}"><span>${esc(label)}</span>${input}</label>`;}
function propertySection(title,content){return `<section class="property-section"><h3><span>⌄</span>${title}</h3>${content}</section>`;}
function renderInspector(){
  const o=selectedObject();document.querySelectorAll('[data-inspector]').forEach(b=>b.classList.toggle('active',b.dataset.inspector===state.inspector));
  if(!o){el('object-heading').innerHTML=`<div class="object-symbol">${icon('project',28)}</div><div><h2>Project overview</h2><p>${esc(store.meta.number)} · Engineering</p></div>`;el('properties').innerHTML=propertySection('Connected project',`<div class="modal-stat-grid" style="grid-template-columns:1fr 1fr;gap:8px;margin:0"><div class="stat-box"><strong>${store.nodes.size}</strong><span>Plant objects</span></div><div class="stat-box"><strong>${store.edges.size}</strong><span>Connections</span></div></div><p class="modal-intro" style="font-size:10px;margin:14px 0">Select an object on the drawing, in the navigator, or in a register to edit its shared attributes.</p><button class="button" data-action="project-info">Project information</button>`)+propertySection('Open drawings',store.documents.map(d=>`<button class="connection-row" data-doc="${esc(d.id)}" style="width:100%;margin:6px 0">${icon('diagram')}<div><strong>${esc(d.code)}</strong><small>${esc(d.name)}</small></div></button>`).join(''));return;}
  const def=TYPES[o.type];el('object-heading').innerHTML=`<div class="object-symbol">${o.kind==='node'?symbolIcon(o.type,35,35):icon(typeIcon(o.type),28)}</div><div><h2>${state.selected.size>1?state.selected.size+' objects':esc(o.tag)}</h2><p>${state.selected.size>1?'Shared batch selection':esc(def?.label||o.description)}</p></div><span class="type-pill">${o.kind==='edge'?'Connection':'Plant object'}</span>`;
  if(state.inspector==='connections'){const edges=o.kind==='edge'?[o]:[...store.edges.values()].filter(e=>e.from.node===o.id||e.to.node===o.id);el('properties').innerHTML=`<div class="property-note">Connections reference object ports. Moving or rotating a connected object updates its routes.</div>`+edges.map(e=>{const source=objectFor(e.from.node),target=objectFor(e.to.node);return`<button class="connection-row" data-focus-object="${esc(e.id)}" style="width:calc(100% - 24px)">${icon(typeIcon(e.type))}<div><strong>${esc(e.tag)}</strong><small>${esc(source?.tag||'Free point')} : ${esc(e.from.port||'—')} → ${esc(target?.tag||'Free point')} : ${esc(e.to.port||'—')}</small></div>${icon('external',12)}</button>`;}).join('')+(!edges.length?'<div class="empty-state">No connections. Use Process pipe or Signal to connect object ports.</div>':'');return;}
  if(state.inspector==='history'){const entries=store.undoStack.filter(p=>[...p.nodes,...p.edges].some(x=>state.selected.has(x.id))).slice().reverse();el('properties').innerHTML=entries.map(p=>`<div class="connection-row">${icon('history')}<div><strong>${esc(p.label)}</strong><small>${new Date(p.time).toLocaleTimeString()} · ${p.nodes.length+p.edges.length} changed objects</small></div></div>`).join('')||'<div class="empty-state">No edits to this object in the current session.</div>';return;}
  const f=(...args)=>propertyField(o,...args);let html='';if(state.selected.size>1)html+='<div class="property-note">Attribute edits apply to all selected objects. Geometry fields apply to the first selected object only.</div>';
  html+=propertySection('Identification',`<div class="property-grid">${f('tag','Object tag','',true)}${f('description','Description','',true)}${f('unit','Unit')}${f('status','Engineering status','',false,['In design','For review','Approved'])}</div>`);
  if(!['text','zone'].includes(o.type)){html+=propertySection(o.kind==='edge'?'Line specification':'Process data',`<div class="property-grid">${o.kind==='edge'?f('props.diameter','Nominal diameter'):f('props.flow','Design flow','m³/h')}${f('props.fluid','Medium')}${f('props.pressure','Operating pressure','bar')}${f('props.temperature','Temperature','°C')}${f('props.designPressure','Design pressure','bar')}${f('props.spec','Pipe class')}</div>`);
    if(['instrument','controller'].includes(o.type))html+=propertySection('Instrumentation',`<div class="property-grid">${f('props.range','Measuring range','',true)}${f('props.signal','Signal type','',false,['','4–20 mA','0–10 V','Digital','HART'])}${f('props.loop','Loop number')}</div>`);
    html+=propertySection('Technical specification',`<div class="property-grid">${f('props.material','Material')}${f('props.manufacturer','Manufacturer')}${['pump','motor','compressor'].includes(o.type)?f('props.power','Rated power','kW')+f('props.speed','Motor speed','rpm'):''}</div>`);
  }
  if(o.kind==='node')html+=propertySection('Placement & geometry',`<div class="property-grid">${f('x','Position X','mm')}${f('y','Position Y','mm')}${f('w','Width','mm')}${f('h','Height','mm')}${f('rotation','Rotation','°')}</div>`);
  const d=store.documents.find(d=>d.id===o.docId);html+=propertySection('References',`<div class="property-reference">${icon('diagram')}<span>${esc(d?.code)} / ${esc(d?.name)}</span></div><button class="button" data-action="datasheet" style="margin-top:10px;width:100%">${icon('document',13)}Open object datasheet</button>`);el('properties').innerHTML=html;
}
function registerRows(kind,global=false){let rows=[];const valid=o=>global||o.docId===state.docId;if(kind==='equipment')rows=[...store.nodes.values()].filter(n=>valid(n)&&['Equipment','Valves','Electrical'].includes(TYPES[n.type].category));if(kind==='instruments')rows=[...store.nodes.values()].filter(n=>valid(n)&&TYPES[n.type].category==='Instrumentation');if(kind==='pipelines')rows=[...store.edges.values()].filter(e=>valid(e)&&e.type!=='signal');return rows;}
const COLUMNS={equipment:[['tag','Object tag',116],['description','Description',240],['type','Object class',128],['unit','Unit',85],['props.pressure','Pressure (bar)',94],['status','Status',100]],instruments:[['tag','Instrument tag',115],['description','Description',230],['props.range','Measuring range',130],['props.signal','Signal',110],['props.loop','Loop',85],['status','Status',100]],pipelines:[['tag','Line designation',205],['from','From',110],['to','To',110],['props.diameter','Diameter',80],['props.spec','Pipe class',90],['props.fluid','Medium',110],['status','Status',100]]};
function columnValue(o,key){if(key.startsWith('props.'))return o.props[key.slice(6)]||'';if(key==='type')return TYPES[o.type]?.label||o.type;if(key==='from'||key==='to')return o[key].node?objectFor(o[key].node)?.tag||'Missing':'Free endpoint';return o[key]??'';}
function statusHTML(status){return `<span class="status-chip ${status==='Approved'?'approved':status==='For review'?'review':''}">● ${esc(status)}</span>`;}
function dataTableHTML(rows,kind){const q=state.tableSearch.toLowerCase();rows=rows.filter(o=>!q||JSON.stringify(o).toLowerCase().includes(q));const cols=COLUMNS[kind];const {key,direction}=state.sort;rows.sort((a,b)=>String(columnValue(a,key)).localeCompare(String(columnValue(b,key)),undefined,{numeric:true})*direction);
  const total=cols.reduce((n,c)=>n+c[2],36);return `<table style="min-width:${Math.min(total,820)}px"><thead><tr><th class="row-number">#</th>${cols.map(([key,label,w])=>`<th data-sort="${key}" style="width:${w/total*100}%">${label}${state.sort.key===key?(state.sort.direction>0?' ↑':' ↓'):''}</th>`).join('')}</tr></thead><tbody>${rows.map((o,i)=>`<tr data-row="${esc(o.id)}" class="${state.selected.has(o.id)?'selected':''}"><td class="row-number">${i+1}</td>${cols.map(([key])=>`<td data-cell="${esc(o.id)}" data-key="${key}" title="${esc(columnValue(o,key))}">${key==='tag'?`<span class="table-tag">${icon(typeIcon(o.type),12)}${esc(o.tag)}</span>`:key==='status'?statusHTML(o.status):esc(columnValue(o,key)||'—')}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cols.length+1}" style="height:70px;text-align:center;color:var(--muted)">No objects in this register.</td></tr>`}</tbody></table>`;
}
function renderTable(){
  const issues=validateEngineering(store);el('equipment-count').textContent=registerRows('equipment').length;el('instrument-count').textContent=registerRows('instruments').length;el('pipeline-count').textContent=registerRows('pipelines').length;el('message-count').textContent=issues.length;
  document.querySelectorAll('[data-table]').forEach(b=>b.classList.toggle('active',b.dataset.table===state.table));el('table-description').textContent=({equipment:'Equipment register',instruments:'Instrument index',pipelines:'Line list',messages:'Engineering consistency checks',history:'Transactional change history'}[state.table])+(state.table==='messages'?' · All documents':' · '+doc().code);
  const area=el('data-table');
  if(COLUMNS[state.table])area.innerHTML=dataTableHTML(registerRows(state.table),state.table);
  else if(state.table==='messages'){const q=state.tableSearch.toLowerCase();const filtered=issues.filter(i=>!q||JSON.stringify(i).toLowerCase().includes(q));area.innerHTML=`<table><thead><tr><th style="width:80px">Severity</th><th style="width:85px">Code</th><th style="width:130px">Object</th><th>Message</th></tr></thead><tbody>${filtered.map(i=>`<tr data-focus-object="${esc(i.objectId)}"><td style="color:${i.severity==='error'?'#af655b':'#b28a4e'}">${icon('warning',12)} ${i.severity}</td><td>${i.code}</td><td>${esc(i.tag)}</td><td title="${esc(i.message)}">${esc(i.message)}</td></tr>`).join('')||'<tr><td colspan="4" style="color:#52977d;text-align:center;height:60px">All configured consistency checks passed.</td></tr>'}</tbody></table>`;}
  else area.innerHTML=`<table><thead><tr><th style="width:95px">Time</th><th>Command</th><th style="width:120px">Changed objects</th></tr></thead><tbody>${[...store.undoStack].reverse().map(p=>`<tr><td>${new Date(p.time).toLocaleTimeString()}</td><td>${esc(p.label)}</td><td>${p.nodes.length+p.edges.length}</td></tr>`).join('')||'<tr><td colspan="3" style="text-align:center;height:60px;color:var(--muted)">Edits are tracked here. Undo and redo are available for the current session.</td></tr>'}</tbody></table>`;
}
function renderRegister(){const target=el('register-view');if(state.view==='documents'){target.innerHTML=`<div class="register-header"><div><h1>Project documents</h1><p>Every drawing is linked to the same engineering object database.</p></div><button class="button primary" data-action="new-document">${icon('plus')}New drawing</button></div><div class="doc-card-grid">${store.documents.map(d=>`<button class="doc-card" data-doc="${esc(d.id)}"><div class="doc-cover">${icon(d.type==='electrical'?'lightning':'diagram',56)}</div><div style="display:flex;justify-content:space-between"><span class="tag">${esc(d.code)}</span><span class="tag">Rev ${esc(d.revision)}</span></div><h3>${esc(d.name)}</h3><p>${[...store.nodes.values()].filter(n=>n.docId===d.id).length} objects · ${d.width} × ${d.height} drawing units</p></button>`).join('')}</div>`;return;}
  const countEquipment=registerRows('equipment',true).length,countInstrument=registerRows('instruments',true).length,countPipe=registerRows('pipelines',true).length,approved=allObjects().filter(o=>o.status==='Approved').length;
  target.innerHTML=`<div class="register-header"><div><h1>Engineering object register</h1><p>One source of truth across ${store.documents.length} documents · ${esc(store.meta.number)}</p></div><div class="register-actions"><button class="button" data-action="export-csv">${icon('export')}Export CSV</button><button class="button primary" data-action="validate">${icon('shield')}Validate</button></div></div><div class="register-stat-row"><div class="register-stat"><div>Equipment ${icon('pump')}</div><strong>${countEquipment}<small>objects</small></strong></div><div class="register-stat"><div>Instrumentation ${icon('instrument')}</div><strong>${countInstrument}<small>instruments</small></strong></div><div class="register-stat"><div>Connections ${icon('pipe')}</div><strong>${countPipe}<small>lines & cables</small></strong></div><div class="register-stat"><div>Engineering status ${icon('check')}</div><strong>${approved}<small>approved</small></strong></div></div><div style="display:flex;gap:6px;margin-bottom:14px">${Object.keys(COLUMNS).map(k=>`<button class="button ${state.activeRegister===k?'primary':''}" data-register-kind="${k}">${k[0].toUpperCase()+k.slice(1)}</button>`).join('')}<input style="margin-left:auto;max-width:220px" id="register-filter" value="${esc(state.tableSearch)}" placeholder="Search register…"></div><div class="register-table">${dataTableHTML(registerRows(state.activeRegister,true),state.activeRegister)}</div>`;
}
function setTable(kind){state.table=kind;el('data-panel').classList.remove('collapsed');renderTable();}
function beginCellEdit(cell){const id=cell.dataset.cell,key=cell.dataset.key,o=objectFor(id);if(!o||['type','from','to'].includes(key))return;const value=columnValue(o,key);const input=document.createElement(key==='status'?'select':'input');input.className='cell-input';if(key==='status')input.innerHTML=['In design','For review','Approved'].map(v=>`<option ${value===v?'selected':''}>${v}</option>`).join('');else input.value=value;cell.textContent='';cell.append(input);input.focus();input.select?.();let done=false;const finish=commit=>{if(done)return;done=true;if(commit&&input.value!==String(value))wrapError(()=>store.transact(`Edit ${o.tag}: ${key}`,()=>store.update(id,key,input.value)));else {renderTable();if(state.view==='register')renderRegister();}};input.addEventListener('blur',()=>finish(true));input.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Enter'){e.preventDefault();finish(true);}if(e.key==='Escape'){e.preventDefault();finish(false);}});}

// ---------- Dialogs, commands and real data exchange ----------
function modal(title,body,onReady=null){const m=el('modal');if(m.open)m.close();el('modal-title').textContent=title;el('modal-body').innerHTML=body;m.showModal();hydrateIcons(m);onReady?.();}
function closeModal(){el('modal').close();}
function actionButtons(primary,label='Save',secondary='Cancel'){return `<div class="modal-actions"><button class="button" data-action="close-modal">${secondary}</button><button class="button primary" id="${primary}">${label}</button></div>`;}
function confirmAction(title,message,button,fn){modal(title,`<p class="modal-intro">${esc(message)}</p>${actionButtons('confirm-action',button)}`,()=>el('confirm-action').onclick=()=>{closeModal();wrapError(fn);});}
function showProject(){modal('Project information',`<p class="modal-intro">Project metadata belongs to the shared model and is included in JSON exports.</p><div class="form-row"><label>Project name</label><input id="edit-project-name" value="${esc(store.meta.name)}"></div><div class="form-grid"><div class="form-row"><label>Project number</label><input id="edit-project-number" value="${esc(store.meta.number)}"></div><div class="form-row"><label>Author</label><input id="edit-project-author" value="${esc(store.meta.author)}"></div></div><div class="form-row"><label>Description</label><textarea id="edit-project-desc">${esc(store.meta.description)}</textarea></div><div class="property-note" style="margin:15px 0">Local-first workspace. There is no remote account, plant connection, or collaboration server in this build.</div>${actionButtons('apply-project')}`,()=>{el('apply-project').onclick=()=>wrapError(()=>{if(!el('edit-project-name').value.trim())throw new Error('A project name is required.');store.transact('Update project information',()=>{store.meta={name:el('edit-project-name').value.trim().slice(0,200),number:el('edit-project-number').value.slice(0,100),author:el('edit-project-author').value.slice(0,100),description:el('edit-project-desc').value.slice(0,2000)};});closeModal();});});}
function newDocument(){modal('Create engineering drawing',`<p class="modal-intro">Add a new drawing to the current project. All objects remain available in the shared registers.</p><div class="form-row"><label>Drawing title</label><input id="new-doc-name" value="New process system"></div><div class="form-grid"><div class="form-row"><label>Drawing number</label><input id="new-doc-code" value="PID-${301+store.documents.length-3}"></div><div class="form-row"><label>Discipline</label><select id="new-doc-type"><option value="pid">Process · P&ID</option><option value="electrical">Electrical · Single line</option></select></div></div>${actionButtons('create-doc','Create drawing')}`,()=>{el('create-doc').onclick=()=>wrapError(()=>{const name=el('new-doc-name').value.trim(),code=el('new-doc-code').value.trim();if(!name||!code)throw new Error('Drawing title and number are required.');if(store.documents.some(d=>d.code===code))throw new Error('That drawing number already exists.');const d={id:uid(),name:name.slice(0,200),code:code.slice(0,50),type:el('new-doc-type').value,revision:'A.01',width:1440,height:900};store.transact('Create drawing',()=>store.documents.push(d));closeModal();state.openDocs.push(d.id);setView('diagram',d.id);});});}
function newProject(){modal('New engineering project',`<p class="modal-intro">Creating a new project replaces the current local workspace. Download a JSON backup first to retain the current project.</p><div class="form-row"><label>Project name</label><input id="new-project-name" value="Untitled plant"></div><div class="form-row"><label>Project number</label><input id="new-project-number" value="NX-001"></div><div class="modal-actions"><button class="button" data-action="export-json">Export current project</button><button class="button" data-action="close-modal">Cancel</button><button class="button primary" id="create-project">Create project</button></div>`,()=>{el('create-project').onclick=()=>wrapError(()=>{const name=el('new-project-name').value.trim();if(!name)throw new Error('A project name is required.');const data={format:'nexora-project',version:1,meta:{name,number:el('new-project-number').value,description:'',author:'Engineer'},documents:[{id:uid(),name:'Process diagram',code:'PID-001',revision:'A.01',type:'pid',width:1440,height:900}],nodes:[],edges:[],revisions:[]};store.load(data);state.openDocs=store.documents.map(d=>d.id);state.selected.clear();closeModal();setView('diagram',store.documents[0].id);toast('New project created. Drag a symbol from the library to begin.');});});}
function showValidation(){const issues=validateEngineering(store),errors=issues.filter(i=>i.severity==='error').length;setTable('messages');modal('Engineering consistency',`<p class="modal-intro">Live checks across all drawings: unique tags, graph connectivity, instrument ranges, pipe classes, and operating/design pressure.</p><div class="modal-stat-grid"><div class="stat-box"><strong>${allObjects().length}</strong><span>Objects checked</span></div><div class="stat-box"><strong style="color:${errors?'#af6659':'#369575'}">${errors}</strong><span>Errors</span></div><div class="stat-box"><strong style="color:#b48a49">${issues.length-errors}</strong><span>Warnings</span></div></div><div class="issue-list">${issues.map(i=>`<div class="issue-card ${i.severity}">${icon('warning')}<div><strong>${esc(i.tag)} · ${i.code}</strong><p>${esc(i.message)}</p></div><button data-focus-object="${esc(i.objectId)}">Locate ${icon('arrow',13)}</button></div>`).join('')||`<div class="empty-state">${icon('shield',32)}<strong>All configured checks passed</strong>The graph is consistent with this build’s validation rules.</div>`}</div><div class="property-note" style="margin:18px 0 0">These are engineering-data checks, not a process-safety analysis or a certified design approval.</div>`);}
function captureRevision(){modal('Capture working-layer baseline',`<p class="modal-intro">A baseline stores the current project graph. Compare future changes or restore it as an undoable transaction.</p><div class="form-row"><label>Revision label</label><input id="revision-label" value="${esc(`Revision ${store.revisions.length+1} · Design review`)}" maxlength="100"></div>${actionButtons('capture-revision-apply','Capture baseline')}`,()=>{el('capture-revision-apply').onclick=()=>{store.captureRevision(el('revision-label').value.trim());closeModal();toast('Revision baseline captured.');};});}
function showRevisions(){modal('Revisions & working layers',`<p class="modal-intro">Local revision snapshots. Comparisons include created, changed, and deleted plant objects and connections. Restoring a baseline is undoable.</p><button class="button primary" data-action="capture-revision">${icon('plus')}Capture current baseline</button>${[...store.revisions].reverse().map(r=>{const diff=store.compareRevision(r),changes=[...diff.nodes,...diff.edges],added=changes.filter(c=>!c.before).length,removed=changes.filter(c=>!c.after).length;return`<div class="revision-row">${icon('history',20)}<div><strong>${esc(r.label)}</strong><small>${new Date(r.created).toLocaleString()} · ${changes.length} changes since baseline</small><small>${added} created · ${changes.length-added-removed} modified · ${removed} deleted</small></div><button data-compare-revision="${esc(r.id)}">Compare</button><button data-restore-revision="${esc(r.id)}">Restore</button></div>`;}).join('')||'<div class="empty-state">No baselines have been captured.</div>'}`);}
function compareRevision(id){const r=store.revisions.find(r=>r.id===id);if(!r)return;const diff=store.compareRevision(r);modal('Compare · '+r.label,`<p class="modal-intro">Current graph compared with the selected baseline.</p><table style="table-layout:auto"><thead><tr><th>Tag</th><th>Change</th><th>Changed attributes</th></tr></thead><tbody>${[...diff.nodes,...diff.edges].map(p=>{const before=p.before,after=p.after,keys=before&&after?[...new Set([...Object.keys(before),...Object.keys(after)])].filter(k=>JSON.stringify(before[k])!==JSON.stringify(after[k])):[];return`<tr><td>${esc((after||before).tag)}</td><td>${!before?'Created':!after?'Deleted':'Modified'}</td><td>${esc(keys.join(', ')||'—')}</td></tr>`;}).join('')||'<tr><td colspan="3" style="height:65px;text-align:center">No object-level differences.</td></tr>'}</tbody></table><div class="modal-actions"><button class="button" data-action="revisions">Back to revisions</button></div>`);}
function showDatasheet(){const o=selectedObject();if(!o){toast('Select an equipment item, instrument, or connection first.');return;}const d=store.documents.find(d=>d.id===o.docId);const rows=[['Object tag',o.tag],['Description',o.description],['Object class',TYPES[o.type]?.label||o.type],['Engineering status',o.status],['Unit',o.unit],['Drawing',`${d.code} · ${d.name}`],...Object.entries(o.props).map(([k,v])=>[k.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase()),v||'Not specified'])];modal('Object datasheet · '+o.tag,`<p class="modal-intro">Generated directly from the project object. No separate copy of engineering attributes is maintained.</p><table class="object-data-table"><tbody>${rows.map(([k,v])=>`<tr><td>${esc(k)}</td><td style="white-space:normal">${esc(v)}</td></tr>`).join('')}</tbody></table><div class="modal-actions"><button class="button" id="datasheet-csv">${icon('export')}Export CSV</button><button class="button primary" id="datasheet-print">${icon('print')}Print datasheet</button></div>`,()=>{el('datasheet-csv').onclick=()=>downloadFile(o.tag+'-datasheet.csv',csv(rows.map(([Attribute,Value])=>({Attribute,Value})),['Attribute','Value']),'text/csv;charset=utf-8');el('datasheet-print').onclick=()=>window.print();});}
function showLayers(){modal('Drawing layers',`<p class="modal-intro">Control visible geometry and labels without changing the underlying project objects. Hidden objects remain in registers and validation.</p><div class="layer-list">${Object.entries({equipment:['Equipment & electrical',PALETTE.ink],piping:['Process piping',PALETTE.pipe],instruments:['Instrumentation & signals',PALETTE.signal],annotations:['Annotations & process areas','#9fb5be']}).map(([key,[name,color]])=>`<label class="layer-item"><span class="layer-swatch" style="background:${color}"></span>${name}<input type="checkbox" data-layer="${key}" ${state.layers[key]?'checked':''}></label>`).join('')}<label class="layer-item">${icon('text')}Object labels<input type="checkbox" id="labels-visible" ${state.labels?'checked':''}></label></div>`);}
function showHelp(){modal('Keyboard & editing guide',`<p class="modal-intro">Drag symbols from the library, or select a symbol and click the drawing. All register and property edits update the same engineering graph.</p><table class="shortcut-table"><tbody>${[['Select / Pan','V / H'],['Pipe / Signal / Cable','P / S / C'],['Text / Rotate / Fit / Grid','T / R / F / G'],['Multi-select','Shift + click'],['Box select','Drag empty drawing'],['Pan without changing tool','Space + drag / Middle mouse'],['Zoom around pointer','Mouse wheel'],['Move selection','Arrow keys · Shift for 10×'],['Undo / Redo','Ctrl/⌘ Z · Ctrl/⌘ Shift Z'],['Copy / Paste / Duplicate','Ctrl/⌘ C · V · D'],['Save / Open','Ctrl/⌘ S · O'],['Search commands & objects','Ctrl/⌘ K'],['Complete line at free point','Enter / Double-click'],['Cancel drawing or edit','Escape'],['Delete selection','Delete / Backspace']].map(([a,b])=>`<tr><td>${a}</td><td><kbd>${b}</kbd></td></tr>`).join('')}</tbody></table><div class="property-note" style="margin:15px 0">Connections snap to circular ports. Drag a selected pipe’s square route handles to edit bends or reconnect endpoints. Drag an object’s corner handles to resize, or its round top handle to rotate. Orthogonal routing does not currently avoid obstacles automatically.</div>`);}
function showAbout(){modal('Nexora Engineering',`<div style="display:flex;align-items:center;gap:14px;margin-bottom:20px"><span class="brand-mark" style="width:54px;height:54px">${icon('project',30)}</span><div><h2 style="margin:0;font-size:25px;font-weight:500">Plant intelligence, connected.</h2><span style="color:#8da0a7;font-size:11px">Version 0.1.0 · Local-first engineering workbench</span></div></div><p class="modal-intro">Independent, COMOS-inspired engineering software built with plain HTML, CSS and JavaScript. Native WebGPU renders vector geometry; Canvas 2D renders labels and interaction overlays, and is the geometry fallback when WebGPU is unavailable.</p><div class="modal-stat-grid"><div class="stat-box"><strong>${Object.keys(TYPES).length}</strong><span>Editable symbol types</span></div><div class="stat-box"><strong>0</strong><span>Runtime dependencies</span></div><div class="stat-box"><strong>v1</strong><span>JSON project schema</span></div></div><p class="modal-intro">Implemented: connected P&ID and electrical drawings, port routing, transforms, undo/redo, object registers, attributes, validation, revision snapshots, local persistence, JSON exchange, CSV, SVG, PNG, basic geometry-only DXF export, and printing.</p><div class="property-note" style="margin:0">This build is not Siemens software, is not affiliated with Siemens, and does not read native COMOS databases. It does not implement process simulation, certified standards libraries, a full 3D plant model, concurrent collaboration, permissions, or enterprise document-control workflows. Sample plant data is illustrative and not for construction.</div><div class="modal-actions"><button class="button" data-action="help">Keyboard shortcuts</button><button class="button primary" data-action="close-modal">Start engineering</button></div>`);}
function exportJSON(){downloadFile(`${store.meta.number||'project'}.nexora.json`,JSON.stringify(store.serialize(),null,2),'application/json');toast('Project JSON exported, including revision snapshots.');}
function exportCSV(kind=state.view==='register'?state.activeRegister:COLUMNS[state.table]?state.table:'equipment'){const rows=registerRows(kind,true);const cols=COLUMNS[kind];downloadFile(`${store.meta.number}-${kind}.csv`,csv(rows.map(o=>Object.fromEntries(cols.map(([k,label])=>[label,columnValue(o,k)]))),cols.map(([,label])=>label)),'text/csv;charset=utf-8');toast(`${rows.length} ${kind} records exported.`);}
function exportScene(){const s=new EngineeringScene();s.update(store,state.docId,state.layers);return s;}
function exportSVG(){const d=doc();downloadFile(d.code+'.svg',geometryToSVG(exportScene(),d,{labels:state.labels}),'image/svg+xml');toast('Drawing exported as editable SVG geometry.');}
async function exportPNG(){const d=doc(),svg=geometryToSVG(exportScene(),d,{labels:state.labels}),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas'),scale=Math.min(2,4096/Math.max(d.width,d.height));canvas.width=Math.round(d.width*scale);canvas.height=Math.round(d.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('PNG encoding failed.');downloadFile(d.code+'.png',blob);toast(`PNG exported at ${canvas.width} × ${canvas.height}.`);}finally{URL.revokeObjectURL(url);}}
function printDrawing(){const d=doc(),svg=geometryToSVG(exportScene(),d,{labels:state.labels});const w=window.open('','_blank');if(!w){toast('Allow pop-ups to print the drawing.',true);return;}w.document.open();w.document.write(`<!doctype html><html><head><title>${esc(d.code)}</title><style>@page{size:landscape;margin:8mm}body{margin:0}svg{display:block;max-width:100%;max-height:95vh;width:100%;height:auto}</style></head><body>${svg}</body></html>`);w.document.close();setTimeout(()=>{w.focus();w.print();},300);}

const COMMANDS=[['new-project','New engineering project','project',''],['open','Open project JSON','folderopen','⌘ O'],['save','Save project locally','save','⌘ S'],['new-document','Create drawing','diagram',''],['register','Open equipment register','table',''],['instrument-register','Open instrument index','instrument',''],['pipeline-register','Open pipeline register','pipe',''],['documents','Project documents','folder',''],['tool-select','Select objects','pointer','V'],['tool-pipe','Route process pipe','pipe','P'],['tool-signal','Route instrument signal','signal','S'],['tool-cable','Route electrical cable','cable','C'],['insert-pump','Insert centrifugal pump','pump',''],['insert-tank','Insert storage tank','tank',''],['insert-valve','Insert gate valve','valve',''],['insert-instrument','Insert field instrument','instrument',''],['tool-text','Add text annotation','text','T'],['fit','Fit drawing to viewport','fit','F'],['undo','Undo last edit','undo','⌘ Z'],['redo','Redo last edit','redo','⌘ ⇧ Z'],['rotate','Rotate selection 90°','rotate','R'],['duplicate','Duplicate selection','copy','⌘ D'],['align-left','Align selected objects left','align',''],['distribute','Distribute selected objects horizontally','distribute',''],['validate','Validate project consistency','shield',''],['capture-revision','Capture revision baseline','history',''],['revisions','Compare or restore revisions','compare',''],['export-json','Export project JSON','database',''],['export-svg','Export drawing SVG','export',''],['export-png','Export drawing PNG','download',''],['export-csv','Export register CSV','table',''],['export-dxf','Export basic DXF geometry','export',''],['layers','Drawing layer visibility','layers',''],['help','Keyboard shortcuts','help','']];
function showSearch(){const p=el('command-palette');if(!p.open)p.showModal();el('command-query').value='';state.paletteIndex=0;searchResults('');el('command-query').focus();}
function searchResults(query){const q=query.toLowerCase().trim(),results=[];for(const [action,label,ico,shortcut]of COMMANDS)if(!q||label.toLowerCase().includes(q))results.push({action,label,ico,shortcut});if(q){const objects=allObjects().filter(o=>`${o.tag} ${o.description}`.toLowerCase().includes(q)).sort((a,b)=>(b.tag.toLowerCase()===q?1:0)-(a.tag.toLowerCase()===q?1:0));for(const o of objects.slice(0,35))results.push({id:o.id,label:o.tag,description:o.description,ico:typeIcon(o.type)});for(const d of store.documents)if(`${d.code} ${d.name}`.toLowerCase().includes(q))results.push({doc:d.id,label:d.code,description:d.name,ico:'diagram'});}state.paletteResults=results.slice(0,45);state.paletteIndex=clamp(state.paletteIndex,0,Math.max(0,state.paletteResults.length-1));el('command-results').innerHTML=state.paletteResults.map((r,i)=>`<button class="command-result ${i===state.paletteIndex?'focused':''}" data-command-index="${i}">${icon(r.ico)}<span>${esc(r.label)} ${r.description?`<small>${esc(r.description)}</small>`:''}</span>${r.shortcut?`<kbd>${r.shortcut}</kbd>`:''}</button>`).join('')||'<div class="empty-state">No matching commands or objects.</div>';}
function chooseSearch(index){const r=state.paletteResults[index];if(!r)return;el('command-palette').close();if(r.action)runAction(r.action);else if(r.doc)setView('diagram',r.doc);else frameObject(r.id);}
const MENUS={
  File:[['new-project','New project','project',''],['new-document','New drawing','diagram',''],['open','Open project…','folderopen','⌘ O'],['save','Save locally','save','⌘ S'],null,['export-json','Export project JSON','database',''],['export-menu','Export drawing…','export',''],['print','Print drawing','print','⌘ P']],
  Edit:[['undo','Undo','undo','⌘ Z'],['redo','Redo','redo','⌘ ⇧ Z'],null,['copy','Copy objects','copy','⌘ C'],['paste','Paste objects','clipboard','⌘ V'],['duplicate','Duplicate','copy','⌘ D'],['delete','Delete','trash','Del'],null,['select-all','Select all visible','pointer','⌘ A'],['rotate','Rotate 90°','rotate','R']],
  View:[['fit','Fit drawing','fit','F'],['zoom-100','Actual size','search',''],['toggle-grid','Toggle drawing grid','grid','G'],['toggle-minimap','Toggle overview','panel',''],['layers','Layers and labels','layers',''],['toggle-table','Toggle data panel','table',''],null,['register','Object register','table',''],['documents','Project documents','folder','']],
  Insert:[['insert-pump','Centrifugal pump','pump',''],['insert-tank','Storage tank','tank',''],['insert-valve','Gate valve','valve',''],['insert-instrument','Field instrument','instrument',''],null,['tool-pipe','Process pipe','pipe','P'],['tool-signal','Instrument signal','signal','S'],['tool-cable','Electrical cable','cable','C'],['tool-text','Text annotation','text','T'],['insert-zone','Process area','box','']],
  Tools:[['validate','Consistency checks','shield',''],['revisions','Revisions','history',''],['datasheet','Object datasheet','document',''],['align-left','Align selected left','align',''],['align-top','Align selected top','align',''],['distribute','Distribute horizontally','distribute',''],['search','Find objects & commands','search','⌘ K']],
  Help:[['help','Keyboard & editing guide','help',''],['project-info','Project information','project',''],['about','About Nexora','info',''],null,['reset-demo','Restore sample project','history','']],
  Export:[['export-json','Project JSON (with graph)','database',''],['export-svg','Drawing SVG','diagram',''],['export-png','Drawing PNG (2×)','download',''],['export-dxf','Basic DXF geometry','export',''],['export-csv','Engineering register CSV','table',''],['print','Print drawing','print','']]
};
function showMenu(name,x,y){const menu=el('menu-popup');menu.innerHTML=(MENUS[name]||[]).map(item=>item?`<button class="menu-item" data-action="${item[0]}">${icon(item[2])}<span>${item[1]}</span><kbd>${item[3]}</kbd></button>`:'<div class="menu-separator"></div>').join('');menu.classList.remove('hidden');menu.style.left=Math.min(x,window.innerWidth-240)+'px';menu.style.top=Math.min(y,window.innerHeight-menu.offsetHeight-15)+'px';}
function closeMenu(){el('menu-popup').classList.add('hidden');}
function requireSelection(){if(!state.selected.size){toast('Select one or more objects first.');return false;}return true;}
function copySelection(){if(!requireSelection())return;const selected=state.selected,nodes=selectionNodes().map(clone),nodeIds=new Set(nodes.map(n=>n.id)),edges=[...store.edges.values()].filter(e=>selected.has(e.id)||(nodeIds.has(e.from.node)&&nodeIds.has(e.to.node))).map(clone);state.clipboard={nodes,edges,offset:0,positions:Object.fromEntries([...store.nodes].map(([id,n])=>[id,clone(n)]))};toast(`${nodes.length+edges.length} objects copied to the workspace clipboard.`);}
function pasteSelection(){const clipboard=state.clipboard;if(!clipboard){toast('Copy some objects first.');return;}const result=[],map=new Map();clipboard.offset+=30;const delta=clipboard.offset;store.transact('Paste objects',()=>{for(const old of clipboard.nodes){const n=clone(old);n.id=uid();n.docId=state.docId;n.tag=store.nextTag(n.type);n.x+=delta;n.y+=delta;store.nodes.set(n.id,n);map.set(old.id,n.id);result.push(n.id);}for(const old of clipboard.edges){const e=clone(old);e.id=uid();e.docId=state.docId;e.tag=store.nextTag('pipe');for(const key of ['from','to']){const p=e[key];if(p.node&&map.has(p.node))e[key]={node:map.get(p.node),port:p.port};else{const point=p.node?portPosition(clipboard.positions[p.node],p.port):p;e[key]={x:point.x+delta,y:point.y+delta};}}e.waypoints=e.waypoints.map(p=>({x:p.x+delta,y:p.y+delta}));store.edges.set(e.id,e);result.push(e.id);}});select(result);setTool('select');}
function alignSelection(axis){const nodes=selectionNodes();if(nodes.length<2){toast('Select at least two equipment objects to align.');return;}const first=nodes[0],target=axis==='x'?first.x-first.w/2:first.y-first.h/2;store.transact(`Align objects ${axis==='x'?'left':'top'}`,()=>{for(const n of nodes)n[axis]=target+(axis==='x'?n.w:n.h)/2;});}
function distributeSelection(){const nodes=selectionNodes().sort((a,b)=>a.x-b.x);if(nodes.length<3){toast('Select at least three objects to distribute.');return;}store.transact('Distribute objects horizontally',()=>{const step=(nodes.at(-1).x-nodes[0].x)/(nodes.length-1),start=nodes[0].x;nodes.forEach((n,i)=>n.x=start+i*step);});}
function toggleFlag(name){state[name]=!state[name];el(name+'-status')?.classList.toggle('enabled',state[name]);if(name==='grid')el('grid-button').classList.toggle('active',state.grid);invalidate();}
const actions={
  'about':showAbout,'help':showHelp,'project-info':showProject,'new-project':newProject,'new-document':newDocument,
  'open':()=>el('project-file').click(),'save':()=>saveLocal(true),'export-json':exportJSON,'export-svg':exportSVG,'export-png':exportPNG,
  'export-csv':()=>exportCSV(),'table-export':()=>{if(state.table==='messages'){const issues=validateEngineering(store);downloadFile('consistency-issues.csv',csv(issues,['severity','code','tag','message']),'text/csv;charset=utf-8');}else if(state.table==='history')downloadFile('change-history.csv',csv(store.undoStack.map(p=>({Time:p.time,Command:p.label,Objects:p.nodes.length+p.edges.length})),['Time','Command','Objects']),'text/csv;charset=utf-8');else exportCSV(state.table);},
  'export-dxf':()=>{downloadFile(doc().code+'.dxf',geometryToDXF(exportScene()),'application/dxf');toast('Basic R12 DXF geometry exported. Engineering relationships are retained only in JSON.');},
  'export-menu':()=>{const r=document.querySelector('[data-action="export-menu"]').getBoundingClientRect();showMenu('Export',r.right-230,r.bottom+5);},'print':printDrawing,
  'register':()=>{state.activeRegister='equipment';setView('register');},'instrument-register':()=>{state.activeRegister='instruments';setView('register');},'pipeline-register':()=>{state.activeRegister='pipelines';setView('register');},'documents':()=>setView('documents'),
  'undo':()=>{cancelInteraction();if(store.undo())toast('Edit undone.');},'redo':()=>{cancelInteraction();if(store.redo())toast('Edit restored.');},
  'delete':()=>{if(requireSelection()){store.transact(`Delete ${state.selected.size} objects`,()=>store.remove(state.selected));select([]);}},
  'rotate':()=>{const nodes=selectionNodes();if(!nodes.length){toast('Select equipment or symbols to rotate.');return;}store.transact('Rotate objects 90°',()=>nodes.forEach(n=>n.rotation=((n.rotation||0)+90)%360));},
  'copy':copySelection,'paste':pasteSelection,'duplicate':()=>{if(requireSelection()){copySelection();pasteSelection();}},
  'select-all':()=>{if(state.sceneDirty)rebuild();select([...scene.entries.keys()]);},'align-left':()=>alignSelection('x'),'align-top':()=>alignSelection('y'),'distribute':distributeSelection,
  'tool-select':()=>setTool('select'),'tool-pipe':()=>setTool('pipe'),'tool-signal':()=>setTool('signal'),'tool-cable':()=>setTool('cable'),'tool-text':()=>setTool('text'),
  'insert-pump':()=>setTool('insert','pump'),'insert-tank':()=>setTool('insert','tank'),'insert-valve':()=>setTool('insert','valve'),'insert-instrument':()=>setTool('insert','instrument'),'insert-zone':()=>setTool('insert','zone'),
  'fit':fit,'zoom-in':()=>{camera.zoomAt({x:camera.width/2,y:camera.height/2},1.2);invalidate();},'zoom-out':()=>{camera.zoomAt({x:camera.width/2,y:camera.height/2},1/1.2);invalidate();},'zoom-100':()=>{camera.zoomAt({x:camera.width/2,y:camera.height/2},1/camera.zoom);invalidate();},
  'toggle-grid':()=>toggleFlag('grid'),'toggle-snap':()=>toggleFlag('snap'),'toggle-ortho':()=>toggleFlag('ortho'),'layers':showLayers,'toggle-table':()=>el('data-panel').classList.toggle('collapsed'),
  'toggle-minimap':()=>{state.minimap=!state.minimap;document.querySelector('.minimap-wrap').classList.toggle('hidden',!state.minimap);invalidate();},
  'navigator-toggle':()=>el('library').classList.toggle('hidden'),'collapse-tree':()=>{if(state.collapsed.size)state.collapsed.clear();else document.querySelectorAll('[data-tree-group]').forEach(b=>state.collapsed.add(b.dataset.treeGroup));renderTree();},
  'library-help':()=>toast('Drag a symbol onto the drawing, or click a symbol then click the drawing. Press Esc to stop placing.'),
  'validate':showValidation,'messages':()=>{setView('diagram',state.docId,false);setTable('messages');},'revisions':showRevisions,'capture-revision':captureRevision,
  'approve':()=>{if(requireSelection())store.transact('Mark objects approved',()=>{for(const id of state.selected)store.update(id,'status','Approved');});},
  'datasheet':showDatasheet,'focus-selection':()=>{if(requireSelection())frameObject([...state.selected][0]);},'search':showSearch,'close-modal':closeModal,
  'reset-demo':()=>confirmAction('Restore sample project','This replaces the current workspace. Export the current project first to keep a backup.','Restore sample',()=>{store.load(makeDemo());state.openDocs=store.documents.map(d=>d.id);state.selected=new Set(['p101a']);setView('diagram',store.documents[0].id);toast('The sample project has been restored.');})
};
function runAction(action){if(!actions[action])return;closeMenu();try{const value=actions[action]();if(value?.catch)value.catch(e=>toast(e.message,true));}catch(error){console.error(error);toast(error.message,true);}}

// ---------- Pointer editing state machine ----------
function insertSymbol(type,p){let node;store.transact(`Insert ${TYPES[type].label}`,()=>{const point=snapped(p);node=store.addNode(type,point.x,point.y,state.docId,{unit:doc().type==='electrical'?'E-100':state.docId==='pid-201'?'U-200':'U-100'});});select([node.id]);return node;}
function insertText(p){const point=snapped(p);modal('Add drawing annotation',`<div class="form-row"><label>Annotation text</label><textarea id="annotation-text" maxlength="2000" placeholder="Enter a process note or annotation…"></textarea></div>${actionButtons('add-annotation','Place annotation')}`,()=>{el('annotation-text').focus();el('add-annotation').onclick=()=>{const value=el('annotation-text').value.trim();if(!value)return;let n;store.transact('Insert annotation',()=>{n=store.addNode('text',point.x,point.y,state.docId,{description:value,w:Math.max(100,Math.min(800,value.length*7))});});closeModal();select([n.id]);setTool('select');};});}
function finishConnection(to){const conn=state.connection;if(!conn)return;const start=endpointWorld(conn.from),end=endpointWorld(to);if(distance(start,end)<1&&conn.waypoints.length===0){toast('Choose a different endpoint.');return;}let edge;store.transact(`Route ${conn.type}`,()=>{edge=store.addEdge(conn.from,to,state.docId,conn.type,conn.waypoints);edge.orthogonal=state.ortho;if(conn.type==='cable'){edge.props.diameter='4×6 mm²';edge.props.fluid='Electrical';}});state.connection=null;select([edge.id]);invalidate();}
overlay.addEventListener('pointerdown',event=>wrapError(()=>{
  if(event.button===2)return;closeMenu();overlay.focus();const point=localPoint(event),p=camera.world(point);state.pointer=p;state.port=findPort(p);
  if(event.button===1||state.space||state.tool==='pan'){event.preventDefault();state.drag={type:'pan',screen:point,camera:{x:camera.x,y:camera.y}};overlay.setPointerCapture(event.pointerId);overlay.style.cursor='grabbing';return;}
  if(event.button!==0)return;
  if(state.tool==='insert'){insertSymbol(state.insertType,p);if(!event.shiftKey)setTool('select');return;}
  if(state.tool==='text'){insertText(p);return;}
  if(['pipe','signal','cable'].includes(state.tool)){
    const end=endpointAt(p);if(!state.connection){state.connection={type:state.tool,from:end,waypoints:[]};el('status-message').textContent='Routing: click bends, a port, or Enter to finish';}
    else if(end.node)finishConnection(end);else{const last=state.connection.waypoints.at(-1);if(!last||distance(last,end)>.01)state.connection.waypoints.push(end);}
    invalidate();return;
  }
  const handle=handleHit(p);
  if(handle){store.begin();const o=objectFor(handle.id);state.drag={...handle,start:p,original:clone(o)};if(handle.type==='waypoint'){o.waypoints=clone(handle.points.slice(1,-1));state.drag.waypointIndex=handle.index-1;}overlay.setPointerCapture(event.pointerId);return;}
  const hit=scene.hit(p,7/camera.zoom);
  if(hit){if(event.shiftKey){if(state.selected.has(hit))state.selected.delete(hit);else state.selected.add(hit);renderSelectionUI();invalidate();return;}
    if(!state.selected.has(hit))select([hit]);const o=objectFor(hit);
    if(o.kind==='node'){store.begin();const originals=selectionNodes().map(clone),moving=new Set(originals.map(n=>n.id));const edgeOriginals=[...store.edges.values()].filter(e=>moving.has(e.from.node)&&moving.has(e.to.node)).map(clone);state.drag={type:'move',start:p,originals,edgeOriginals,moved:false};overlay.setPointerCapture(event.pointerId);}
  }else {if(!event.shiftKey)select([]);state.marquee={start:p,end:p,add:event.shiftKey,previous:new Set(state.selected)};state.drag={type:'marquee'};overlay.setPointerCapture(event.pointerId);}
}));
overlay.addEventListener('pointermove',event=>wrapError(()=>{
  const point=localPoint(event),p=camera.world(point);state.pointer=p;el('cursor-position').textContent=`X: ${p.x.toFixed(2)}   Y: ${p.y.toFixed(2)}`;
  const drag=state.drag;
  if(drag?.type==='pan'){camera.x=drag.camera.x-(point.x-drag.screen.x)/camera.zoom;camera.y=drag.camera.y-(point.y-drag.screen.y)/camera.zoom;invalidate();return;}
  if(drag?.type==='move'){let dx=p.x-drag.start.x,dy=p.y-drag.start.y;if(event.shiftKey){if(Math.abs(dx)>Math.abs(dy))dy=0;else dx=0;}if(state.snap){dx=snap(dx);dy=snap(dy);}for(const original of drag.originals){const n=store.nodes.get(original.id);n.x=original.x+dx;n.y=original.y+dy;}for(const original of drag.edgeOriginals){const e=store.edges.get(original.id);e.waypoints=original.waypoints.map(p=>({x:p.x+dx,y:p.y+dy}));}drag.moved||=Math.abs(dx)+Math.abs(dy)>0;invalidate({scene:true});return;}
  if(drag?.type==='resize'){const n=store.nodes.get(drag.id),angle=-(n.rotation||0)*Math.PI/180,dx=p.x-n.x,dy=p.y-n.y;let w=Math.abs(dx*Math.cos(angle)-dy*Math.sin(angle))*2,h=Math.abs(dx*Math.sin(angle)+dy*Math.cos(angle))*2;if(event.shiftKey){const aspect=drag.original.w/drag.original.h;h=w/aspect;}n.w=clamp(state.snap?snap(w):w,6,10000);n.h=clamp(state.snap?snap(h):h,6,10000);invalidate({scene:true});return;}
  if(drag?.type==='rotate'){const n=store.nodes.get(drag.id);const angle=Math.atan2(p.y-n.y,p.x-n.x)*180/Math.PI+90;n.rotation=((state.snap?snap(angle,15):angle)+360)%360;invalidate({scene:true});return;}
  if(drag?.type==='waypoint'){const e=store.edges.get(drag.id);e.waypoints[drag.waypointIndex]=snapped(p);invalidate({scene:true});return;}
  if(drag?.type==='endpoint'){const e=store.edges.get(drag.id);state.port=findPort(p);e[drag.end]=endpointAt(p);invalidate({scene:true});return;}
  if(drag?.type==='marquee'){state.marquee.end=p;invalidate();return;}
  const hit=scene.hit(p,7/camera.zoom);state.port=findPort(p);if(hit!==state.hover){state.hover=hit;invalidate();}
  if(state.tool==='select')overlay.style.cursor=handleHit(p)?'crosshair':hit?'move':'default';if(state.connection||state.tool==='insert'||state.port)invalidate();
}));
overlay.addEventListener('pointerup',event=>wrapError(()=>{
  const drag=state.drag;if(!drag)return;
  if(drag.type==='marquee'&&state.marquee){const {start:a,end:b,previous,add}=state.marquee;const bounds={x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),maxX:Math.max(a.x,b.x),maxY:Math.max(a.y,b.y)};const hits=scene.index.query(bounds);const chosen=[...hits].filter(id=>{const o=objectFor(id);if(o?.kind!=='node'||o.type==='zone')return false;return o.x>=bounds.x&&o.x<=bounds.maxX&&o.y>=bounds.y&&o.y<=bounds.maxY;});select(add?[...previous,...chosen]:chosen);state.marquee=null;}
  if(store.pending)store.commit(({move:'Move objects',resize:'Resize symbol',rotate:'Rotate symbol',waypoint:'Edit line route',endpoint:'Reconnect line'})[drag.type]||'Edit drawing');
  state.drag=null;if(overlay.hasPointerCapture(event.pointerId))overlay.releasePointerCapture(event.pointerId);overlay.style.cursor=state.tool==='pan'?'grab':'default';invalidate({scene:true,ui:true});
}));
overlay.addEventListener('pointercancel',()=>cancelInteraction());
overlay.addEventListener('lostpointercapture',()=>{if(state.drag)cancelInteraction();});
overlay.addEventListener('pointerleave',()=>{if(!state.drag){state.hover=null;state.port=null;if(!state.connection)state.pointer=null;invalidate();}});
overlay.addEventListener('wheel',event=>{event.preventDefault();camera.zoomAt(localPoint(event),Math.exp(-clamp(event.deltaY,-160,160)*.002));invalidate();},{passive:false});
overlay.addEventListener('dblclick',event=>{const p=camera.world(localPoint(event));if(state.connection){const to=endpointAt(p);if(state.connection.waypoints.length&&distance(state.connection.waypoints.at(-1),endpointWorld(to))<1)state.connection.waypoints.pop();finishConnection(to);return;}const id=scene.hit(p,7/camera.zoom);if(id){select([id]);showDatasheet();}});
overlay.addEventListener('contextmenu',event=>{event.preventDefault();const id=scene.hit(camera.world(localPoint(event)),7/camera.zoom);if(id&&!state.selected.has(id))select([id]);showMenu('Edit',event.clientX,event.clientY);});
editor.addEventListener('dragover',event=>{if(event.dataTransfer.types.includes('application/x-nexora-symbol')){event.preventDefault();event.dataTransfer.dropEffect='copy';}});
editor.addEventListener('drop',event=>{event.preventDefault();const type=event.dataTransfer.getData('application/x-nexora-symbol');if(Object.hasOwn(TYPES,type)){insertSymbol(type,camera.world(localPoint(event)));setTool('select');}});
el('minimap').addEventListener('pointerdown',event=>{const rect=el('minimap').getBoundingClientRect(),d=doc(),scale=Math.min((180-14)/d.width,(108-12)/d.height),ox=(180-d.width*scale)/2,oy=(108-d.height*scale)/2;camera.x=((event.clientX-rect.left)/rect.width*180-ox)/scale;camera.y=((event.clientY-rect.top)/rect.height*108-oy)/scale;invalidate();});

// ---------- DOM event routing ----------
document.addEventListener('click',event=>{
  const target=event.target.closest('button,[data-row],[data-focus-object],[data-sort],[data-close-doc]');if(!target){if(!event.target.closest('#menu-popup'))closeMenu();return;}
  const d=target.dataset;
  if(d.closeDoc){event.stopPropagation();state.openDocs=state.openDocs.filter(id=>id!==d.closeDoc);if(d.closeDoc===state.docId){const next=state.openDocs[0];if(next)setView('diagram',next);else setView('documents');}else renderDocumentTabs();return;}
  if(d.action){runAction(d.action);return;}
  if(d.menu){const r=target.getBoundingClientRect();showMenu(d.menu,r.left,r.bottom+3);return;}
  if(d.ribbon){state.ribbon=d.ribbon;renderRibbon();return;}
  if(d.doc){setView('diagram',d.doc);return;}
  if(d.tool){setTool(d.tool);return;}
  if(d.symbol){setTool('insert',d.symbol);if(state.view!=='diagram')setView('diagram');return;}
  if(d.library){state.library=d.library;renderLibrary();return;}
  if(d.nav){state.nav=d.nav;renderTree();return;}
  if(d.treeGroup){state.collapsed.has(d.treeGroup)?state.collapsed.delete(d.treeGroup):state.collapsed.add(d.treeGroup);renderTree();return;}
  if(d.object){const o=objectFor(d.object);if(!o)return;if(o.docId!==state.docId)setView('diagram',o.docId);select([o.id],{add:event.shiftKey});return;}
  if(d.focusObject){closeModal();frameObject(d.focusObject);return;}
  if(d.inspector){state.inspector=d.inspector;renderInspector();return;}
  if(d.table){setTable(d.table);return;}
  if(d.registerKind){state.activeRegister=d.registerKind;renderRegister();return;}
  if(d.row&&!event.target.closest('input,select')){select([d.row],{add:event.shiftKey});return;}
  if(d.sort){state.sort={key:d.sort,direction:state.sort.key===d.sort?-state.sort.direction:1};renderTable();if(state.view==='register')renderRegister();return;}
  if(d.commandIndex!==undefined){chooseSearch(Number(d.commandIndex));return;}
  if(d.compareRevision){compareRevision(d.compareRevision);return;}
  if(d.restoreRevision){const r=store.revisions.find(r=>r.id===d.restoreRevision);confirmAction('Restore revision',`Restore “${r.label}”? This replaces the current graph. You can undo the restoration.`,'Restore revision',()=>{store.restoreRevision(d.restoreRevision);setView('diagram',store.documents[0].id);toast('Revision restored.');});}
});
document.addEventListener('dblclick',event=>{const cell=event.target.closest('[data-cell]');if(cell)beginCellEdit(cell);const tree=event.target.closest('[data-object]');if(tree)frameObject(tree.dataset.object);});
document.addEventListener('change',event=>wrapError(()=>{
  const target=event.target;if(target.dataset.property){const key=target.dataset.property,value=target.value;const ids=key.startsWith('props.')||['status','unit','description'].includes(key)?[...state.selected]:[target.dataset.id];store.transact(`Edit ${key}`,()=>{for(const id of ids)store.update(id,key,value);});}
  if(target.dataset.layer){state.layers[target.dataset.layer]=target.checked;invalidate({scene:true});}
  if(target.id==='labels-visible'){state.labels=target.checked;invalidate();}
}));
document.addEventListener('dragstart',event=>{const symbol=event.target.closest('[data-symbol]');if(symbol){event.dataTransfer.setData('application/x-nexora-symbol',symbol.dataset.symbol);event.dataTransfer.effectAllowed='copy';}});
el('tree-search').addEventListener('input',event=>{state.treeSearch=event.target.value;renderTree();});
el('table-search').addEventListener('input',event=>{state.tableSearch=event.target.value;renderTable();});
document.addEventListener('input',event=>{if(event.target.id==='register-filter'){state.tableSearch=event.target.value;const table=el('register-view').querySelector('.register-table');if(table)table.innerHTML=dataTableHTML(registerRows(state.activeRegister,true),state.activeRegister);}});
el('command-query').addEventListener('input',event=>{state.paletteIndex=0;searchResults(event.target.value);});
el('command-query').addEventListener('keydown',event=>{if(['ArrowDown','ArrowUp','Enter'].includes(event.key)){event.preventDefault();if(event.key==='Enter')chooseSearch(state.paletteIndex);else{state.paletteIndex=clamp(state.paletteIndex+(event.key==='ArrowDown'?1:-1),0,state.paletteResults.length-1);searchResults(event.target.value);el('command-results').querySelector('.focused')?.scrollIntoView({block:'nearest'});}}});
el('project-file').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{if(file.size>40*1024*1024)throw new Error('Project files are limited to 40 MB.');const data=validateProject(JSON.parse(await file.text()));confirmAction('Open project',`Open “${data.meta.name}”? This replaces the current workspace. Export the current project first to retain it.`,'Open project',()=>{store.load(data);state.openDocs=store.documents.map(d=>d.id);state.selected.clear();setView('diagram',store.documents[0].id);toast('Project imported and validated.');});}catch(error){toast('Import failed: '+error.message,true);}});

function nudge(dx,dy){if(!state.selected.size)return;store.transact('Nudge selection',()=>{for(const n of selectionNodes()){n.x+=dx;n.y+=dy;}for(const id of state.selected){const e=store.edges.get(id);if(!e)continue;for(const key of ['from','to'])if(!e[key].node){e[key].x+=dx;e[key].y+=dy;}e.waypoints=e.waypoints.map(p=>({x:p.x+dx,y:p.y+dy}));}});}
document.addEventListener('keydown',event=>{
  const inInput=event.target.closest('input,textarea,select,[contenteditable="true"]'),cmd=event.metaKey||event.ctrlKey,key=event.key.toLowerCase();
  if(cmd&&key==='k'){event.preventDefault();showSearch();return;}
  if(el('modal').open||el('command-palette').open)return;
  if(inInput)return;
  if(cmd){const map={s:'save',o:'open',z:event.shiftKey?'redo':'undo',y:'redo',a:'select-all',c:'copy',v:'paste',d:'duplicate',p:'print'};if(map[key]){event.preventDefault();runAction(map[key]);return;}}
  if(key==='escape'){event.preventDefault();cancelInteraction();setTool('select');closeMenu();return;}
  if(event.code==='Space'){event.preventDefault();state.space=true;overlay.style.cursor='grab';return;}
  if(key==='enter'&&state.connection&&state.pointer){event.preventDefault();finishConnection(endpointAt(state.pointer));return;}
  if(['delete','backspace'].includes(key)){event.preventDefault();runAction('delete');return;}
  if(key.startsWith('arrow')){event.preventDefault();const step=(state.snap?10:1)*(event.shiftKey?10:1);wrapError(()=>nudge(key==='arrowleft'?-step:key==='arrowright'?step:0,key==='arrowup'?-step:key==='arrowdown'?step:0));return;}
  if(key==='/'){event.preventDefault();el('tree-search').focus();return;}
  const shortcuts={v:'tool-select',p:'tool-pipe',s:'tool-signal',c:'tool-cable',t:'tool-text',f:'fit',r:'rotate',g:'toggle-grid'};if(shortcuts[key]){event.preventDefault();runAction(shortcuts[key]);}if(key==='h'){event.preventDefault();setTool('pan');}
});
document.addEventListener('keyup',event=>{if(event.code==='Space'){state.space=false;overlay.style.cursor=state.tool==='pan'?'grab':'default';}});
window.addEventListener('blur',()=>{state.space=false;if(state.drag)cancelInteraction();});
for(const [selector,property,axis,min,max,invert]of[['.left-resize','--left-width','x',180,400,false],['.right-resize','--right-width','x',220,420,true],['.bottom-resize','--data-height','y',34,420,true]]){
  const handle=document.querySelector(selector);handle.addEventListener('pointerdown',event=>{event.preventDefault();const start=axis==='x'?event.clientX:event.clientY;const current=parseFloat(getComputedStyle(document.documentElement).getPropertyValue(property));handle.setPointerCapture(event.pointerId);const move=e=>{const delta=((axis==='x'?e.clientX:e.clientY)-start)*(invert?-1:1);document.documentElement.style.setProperty(property,clamp(current+delta,min,max)+'px');};const end=e=>{handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',end);handle.removeEventListener('pointercancel',end);if(handle.hasPointerCapture(e.pointerId))handle.releasePointerCapture(e.pointerId);};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end);});
}

hydrateIcons();renderRibbon();renderLibrary();renderUI();resize();fit();state.uiDirty=false;invalidate({scene:true});
await renderer.ready;resize();invalidate();
// Deliberately exposed development surface for deterministic integration tests and custom integrations.
window.nexora={store,scene,camera,renderer,state,actions,runAction,select,setView,fit,frameObject,validate:()=>validateEngineering(store),save:saveLocal,exportProject:()=>store.serialize(),ready:true};
